/**
 * PBMP Form / Style Template model (UI prototype)
 * Source: GAP-FORM-TEMPLATE-001 — full scope from user-shared specification
 */

export const FUNCTIONALITY = {
  id: 'func-monthly-sales',
  name: 'Show monthly sales performance',
  chartGoal: 'Display the monthly sales trend as a chart / table / KPI / text package.',
  definition:
    'One Functionality → one functional definition → one underlying content/data structure → multiple Form Variants, each controlled by a Form-specific / Style Template.',
  unchanged: [
    'Sales data (Month × Sales)',
    'X-axis / category meaning (Month)',
    'Y-axis / measure meaning (Sales ₹ lakh)',
    'Calculations / aggregation intent',
    'Filtering behaviour (none applied in demo)',
    'Drill-down / analytical purpose',
    'Intended information result',
  ],
  changesWithForm: [
    'Packaging / rendering type (Line, Bar, Table, KPI, Text)',
    'How values are visually encoded',
  ],
  changesWithStyle: [
    'Background, font, colours, spacing',
    'Legend, grid, markers, borders',
    'Theme, accessibility, print/mobile rules',
  ],
};

/** Functional Definition — behaviour stays fixed across Forms */
export const FUNCTIONAL_DEFINITION = {
  dataSource: 'Inline demo dataset — Monthly Sales',
  categoryField: 'Month',
  measureField: 'Sales (₹ lakh)',
  aggregation: 'None (raw monthly values)',
  sorting: 'Calendar month order',
  filters: 'None',
  xAxis: 'Month',
  yAxis: 'Sales',
  tooltipBehaviour: 'Show month + sales on hover (charts)',
  interactionBehaviour: 'Hover highlight; Form/Style switches do not mutate data',
};

export const SALES_DATA = [
  { month: 'January', sales: 10 },
  { month: 'February', sales: 14 },
  { month: 'March', sales: 12 },
  { month: 'April', sales: 18 },
];

export const SENTENCE_EXAMPLE = {
  content: 'Sales increased by 15% this month.',
  note:
    'Declarative vs interrogative would normally be linguistic functionality / sentence configuration — not merely a Form change.',
  formDiffersThrough: [
    'background',
    'font',
    'font size',
    'font colour',
    'emphasis',
    'border',
    'alignment',
    'spacing',
    'placement',
    'mobile versus desktop layout',
    'document, dashboard, or presentation styling',
  ],
};

export const FORM_TYPES = [
  {
    id: 'line_chart',
    label: 'Line Chart',
    family: 'chart',
    description: 'Trend packaging of the same sales series',
  },
  {
    id: 'bar_chart',
    label: 'Bar Chart',
    family: 'chart',
    description: 'Comparison packaging of the same sales series',
  },
  {
    id: 'table',
    label: 'Table',
    family: 'tabular',
    description: 'Row/column packaging of the same sales series',
  },
  {
    id: 'kpi_card',
    label: 'KPI Card',
    family: 'summary',
    description: 'Summary packaging — latest value + trend',
  },
  {
    id: 'text',
    label: 'Text',
    family: 'text',
    description: 'Narrative packaging of the same sales meaning',
  },
];

function baseTokens(overrides) {
  return {
    surfaceBackground: '#ffffff',
    primaryDataColour: '#2563eb',
    primaryTextColour: '#374151',
    secondaryTextColour: '#6b7280',
    titleColour: '#374151',
    titleSize: 18,
    titleWeight: 600,
    fontFamily: 'Inter, Segoe UI, system-ui, sans-serif',
    axisText: '#6b7280',
    gridColour: '#e5e7eb',
    gridStyle: 'thin',
    gridVisibility: true,
    legendPosition: 'top-right',
    legendCollapsed: false,
    tooltipSurface: '#ffffff',
    tooltipText: '#111827',
    tooltipShadow: '0 4px 14px rgba(15, 23, 42, 0.12)',
    borderTreatment: 'subtle',
    borderColour: '#d1d5db',
    markerColour: '#2563eb',
    markerShape: 'circle',
    markerSize: 5,
    barRadius: 6,
    lineWidth: 2,
    lineStyle: 'solid',
    emphasisThickness: 2,
    areaFill: false,
    areaFillOpacity: 0.12,
    padding: 16,
    shadow: true,
    animation: true,
    axisLabelDensity: 'normal',
    highContrast: false,
    logo: false,
    brandedTitleArea: false,
    compact: false,
    ...overrides,
  };
}

/**
 * Universal Style Templates — reusable tokens (not chart-type-specific).
 * Includes all Form variants from the shared Line Chart example + Executive Light.
 */
export const STYLE_TEMPLATES = {
  corporate_light: {
    id: 'corporate_light',
    name: 'Corporate Light',
    purpose: 'Standard corporate reports',
    variantRow: {
      background: 'White',
      font: 'Arial',
      linePresentation: 'Solid line',
      other: 'Grey grid, legend at top',
    },
    tokens: baseTokens({
      fontFamily: 'Arial, Helvetica, sans-serif',
      surfaceBackground: '#ffffff',
      primaryDataColour: '#2563eb',
      gridColour: '#d1d5db',
      legendPosition: 'top',
    }),
  },
  executive_light: {
    id: 'executive_light',
    name: 'Executive Light',
    purpose: 'Reports, daytime dashboards and printing',
    variantRow: {
      background: 'White',
      font: 'Inter',
      linePresentation: 'Solid PBMP-blue line',
      other: 'Light grey grid, legend top-right',
    },
    tokens: baseTokens({}),
  },
  executive_dark: {
    id: 'executive_dark',
    name: 'Executive Dark',
    purpose: 'Executive dashboards, control rooms and dark mode',
    variantRow: {
      background: 'Dark grey / charcoal',
      font: 'Inter',
      linePresentation: 'Bright cyan line',
      other: 'Minimal grid, large KPI labels',
    },
    tokens: baseTokens({
      surfaceBackground: '#1f2937',
      primaryDataColour: '#22d3ee',
      primaryTextColour: '#f9fafb',
      secondaryTextColour: '#d1d5db',
      titleColour: '#ffffff',
      axisText: '#d1d5db',
      gridColour: '#374151',
      gridStyle: 'subtle',
      tooltipSurface: '#111827',
      tooltipText: '#f3f4f6',
      tooltipShadow: '0 4px 14px rgba(0, 0, 0, 0.45)',
      borderTreatment: 'none',
      borderColour: 'transparent',
      markerColour: '#22d3ee',
      shadow: false,
      titleSize: 20,
    }),
  },
  pbmp_branded: {
    id: 'pbmp_branded',
    name: 'PBMP Branded',
    purpose: 'Brand-forward dashboards and stakeholder decks',
    variantRow: {
      background: 'PBMP background',
      font: 'PBMP font',
      linePresentation: 'Brand-styled line',
      other: 'Logo, branded title area',
    },
    tokens: baseTokens({
      surfaceBackground: 'linear-gradient(160deg, #0b1f3a 0%, #123456 55%, #0e7490 100%)',
      primaryDataColour: '#67e8f9',
      primaryTextColour: '#ecfeff',
      secondaryTextColour: '#a5f3fc',
      titleColour: '#ffffff',
      fontFamily: 'DM Sans, Inter, system-ui, sans-serif',
      axisText: '#a5f3fc',
      gridColour: 'rgba(165, 243, 252, 0.25)',
      tooltipSurface: '#082f49',
      tooltipText: '#ecfeff',
      borderTreatment: 'none',
      markerColour: '#67e8f9',
      logo: true,
      brandedTitleArea: true,
      shadow: true,
    }),
  },
  presentation: {
    id: 'presentation',
    name: 'Presentation Form',
    purpose: 'Large-screen presentations',
    variantRow: {
      background: 'Transparent / light',
      font: 'Large font',
      linePresentation: 'Thick line',
      other: 'Fewer axis labels',
    },
    tokens: baseTokens({
      surfaceBackground: '#f8fafc',
      primaryDataColour: '#1d4ed8',
      titleSize: 26,
      lineWidth: 4,
      emphasisThickness: 4,
      markerSize: 7,
      axisLabelDensity: 'sparse',
      padding: 28,
      fontFamily: 'Georgia, "Times New Roman", serif',
    }),
  },
  mobile: {
    id: 'mobile',
    name: 'Mobile Form',
    purpose: 'Compact phone / small viewport',
    variantRow: {
      background: 'Compact',
      font: 'Smaller responsive font',
      linePresentation: 'Simplified line',
      other: 'Collapsed legend',
    },
    tokens: baseTokens({
      titleSize: 14,
      lineWidth: 2,
      markerSize: 4,
      legendCollapsed: true,
      compact: true,
      padding: 10,
      axisLabelDensity: 'sparse',
      barRadius: 4,
    }),
  },
  accessible: {
    id: 'accessible',
    name: 'Accessible Form',
    purpose: 'High-contrast readable presentation',
    variantRow: {
      background: 'High contrast',
      font: 'Large readable font',
      linePresentation: 'Thick distinguishable line',
      other: 'Enhanced labels and markers',
    },
    tokens: baseTokens({
      surfaceBackground: '#000000',
      primaryDataColour: '#fde047',
      primaryTextColour: '#ffffff',
      secondaryTextColour: '#fef08a',
      titleColour: '#ffffff',
      titleSize: 22,
      axisText: '#ffffff',
      gridColour: '#525252',
      markerColour: '#fde047',
      markerSize: 8,
      lineWidth: 4,
      emphasisThickness: 4,
      highContrast: true,
      tooltipSurface: '#171717',
      tooltipText: '#ffffff',
      borderTreatment: 'subtle',
      borderColour: '#fde047',
      fontFamily: 'Verdana, Geneva, sans-serif',
    }),
  },
  print: {
    id: 'print',
    name: 'Print Form',
    purpose: 'Print-safe black/grey output',
    variantRow: {
      background: 'White',
      font: 'Print-safe font',
      linePresentation: 'Black / grey line styles',
      other: 'No animation or hover controls',
    },
    tokens: baseTokens({
      surfaceBackground: '#ffffff',
      primaryDataColour: '#111827',
      primaryTextColour: '#111827',
      secondaryTextColour: '#4b5563',
      titleColour: '#111827',
      axisText: '#4b5563',
      gridColour: '#9ca3af',
      markerColour: '#111827',
      tooltipSurface: '#ffffff',
      tooltipText: '#111827',
      animation: false,
      shadow: false,
      fontFamily: 'Times New Roman, Times, serif',
      lineStyle: 'solid',
    }),
  },
};

export const TOKEN_INTERPRETATION = [
  {
    token: 'Primary data colour',
    line_chart: 'Line colour',
    bar_chart: 'Bar fill colour',
    table: 'Value emphasis colour',
    kpi_card: 'KPI number colour',
    text: 'Highlighted value colour',
  },
  {
    token: 'Emphasis thickness',
    line_chart: 'Line width',
    bar_chart: 'Bar visual weight',
    table: 'Header / row weight',
    kpi_card: 'KPI number weight',
    text: 'Emphasis weight',
  },
  {
    token: 'Data marker style',
    line_chart: 'Point marker',
    bar_chart: 'Bar-end / value marker',
    table: 'Cell badge / indicator',
    kpi_card: 'Trend arrow style',
    text: 'Inline emphasis mark',
  },
  {
    token: 'Surface background',
    line_chart: 'Chart background',
    bar_chart: 'Chart background',
    table: 'Table surface',
    kpi_card: 'Card surface',
    text: 'Content background',
  },
  {
    token: 'Grid colour',
    line_chart: 'Axis grid',
    bar_chart: 'Axis grid',
    table: 'Row / column rules',
    kpi_card: '— (usually none)',
    text: '— (not applicable)',
  },
];

export const TEMPLATE_LAYERS = [
  {
    id: 'universal',
    name: 'Universal Style Template',
    purpose: 'Attributes reusable across all Forms',
    examples: 'Background, font, border, spacing, shadow, title style',
  },
  {
    id: 'family',
    name: 'Form-Family Template',
    purpose: 'Attributes shared by related Forms',
    examples: 'Axes, grids, legends and tooltips for charts; row rules for tables',
  },
  {
    id: 'type',
    name: 'Form-Type Template',
    purpose: 'Attributes unique to a specific Form',
    examples: 'Line width · bar width · paragraph spacing · KPI trend layout',
  },
];

export const PRINCIPLES = [
  {
    title: 'Form vs Functionality',
    body: 'Form is presentation/appearance. Underlying functionality, data, logic, and intended result remain unchanged.',
  },
  {
    title: 'Two variation levels',
    body: '1) Style variation within the same Form (Line → restyled Line). 2) Form Type change with same data (Line → Bar → Table → KPI).',
  },
  {
    title: 'Style = tokens, not chart type',
    body: 'Style Templates define reusable intentions (colours, surfaces, typography). Each Form Type interprets those tokens.',
  },
  {
    title: 'Three-layer inheritance',
    body: 'Universal Style → Form-Family → Form-Type. Same Executive Dark can style Line, Bar, KPI, Table, Text.',
  },
];

/** Attribute matrix: ✓ / △ / — (Line/Bar/Text as specified; Table & KPI extended) */
export const ATTRIBUTE_MATRIX = [
  { group: 'Common container', attribute: 'Background colour', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Background of the component or content area' },
  { group: 'Common container', attribute: 'Background image/gradient', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Decorative or branded background' },
  { group: 'Common container', attribute: 'Width', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Component width' },
  { group: 'Common container', attribute: 'Height', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Component height' },
  { group: 'Common container', attribute: 'Padding', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Space inside the component boundary' },
  { group: 'Common container', attribute: 'Margin', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Space outside the component' },
  { group: 'Common container', attribute: 'Border colour', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Container-border colour' },
  { group: 'Common container', attribute: 'Border width', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Container-border thickness' },
  { group: 'Common container', attribute: 'Border style', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Solid, dotted, dashed, etc.' },
  { group: 'Common container', attribute: 'Border radius', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Corner roundness' },
  { group: 'Common container', attribute: 'Shadow', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Container elevation or shadow' },
  { group: 'Common container', attribute: 'Opacity', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Transparency of the component' },
  { group: 'Common typography', attribute: 'Font family', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Font used for titles, labels, values or text' },
  { group: 'Common typography', attribute: 'Font size', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Text size' },
  { group: 'Common typography', attribute: 'Font weight', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Regular, medium, bold, etc.' },
  { group: 'Common typography', attribute: 'Font style', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Normal, italic, etc.' },
  { group: 'Common typography', attribute: 'Text colour', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Colour of titles, labels or content' },
  { group: 'Common typography', attribute: 'Text alignment', line_chart: '△', bar_chart: '△', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Chart-title/label alignment or paragraph alignment' },
  { group: 'Common typography', attribute: 'Letter spacing', line_chart: '△', bar_chart: '△', table: '△', kpi_card: '△', text: '✓', meaning: 'Spacing between characters' },
  { group: 'Common typography', attribute: 'Line height', line_chart: '△', bar_chart: '△', table: '△', kpi_card: '△', text: '✓', meaning: 'Spacing between lines of text' },
  { group: 'Common typography', attribute: 'Text decoration', line_chart: '△', bar_chart: '△', table: '△', kpi_card: '—', text: '✓', meaning: 'Underline, strike-through, etc.' },
  { group: 'Title and description', attribute: 'Title visibility', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Whether the component title appears' },
  { group: 'Title and description', attribute: 'Title text', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Displayed heading' },
  { group: 'Title and description', attribute: 'Title position', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Top, bottom, left, centre, etc.' },
  { group: 'Title and description', attribute: 'Subtitle', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Supporting explanatory text' },
  { group: 'Title and description', attribute: 'Description', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Additional context' },
  { group: 'Data mapping', attribute: 'Data source', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Source from which content is obtained' },
  { group: 'Data mapping', attribute: 'Category/dimension field', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '△', text: '△', meaning: 'X-axis category, bar category or text grouping' },
  { group: 'Data mapping', attribute: 'Measure/value field', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Numeric value displayed' },
  { group: 'Data mapping', attribute: 'Aggregation', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '✓', text: '△', meaning: 'Sum, average, count, minimum, maximum, etc.' },
  { group: 'Data mapping', attribute: 'Sorting', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '△', text: '△', meaning: 'Ordering of points, bars or text items' },
  { group: 'Data mapping', attribute: 'Filtering', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Rules controlling displayed content' },
  { group: 'Data mapping', attribute: 'Number format', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Currency, percentage, decimal, compact number, etc.' },
  { group: 'Data mapping', attribute: 'Date format', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '△', text: '✓', meaning: 'Date presentation' },
  { group: 'Axes', attribute: 'X-axis visibility', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Whether the X-axis is shown' },
  { group: 'Axes', attribute: 'Y-axis visibility', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Whether the Y-axis is shown' },
  { group: 'Axes', attribute: 'Axis title', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Description of the axis' },
  { group: 'Axes', attribute: 'Axis label colour', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Colour of tick labels' },
  { group: 'Axes', attribute: 'Axis label font', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Font used for tick labels' },
  { group: 'Axes', attribute: 'Axis line colour', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Colour of the axis line' },
  { group: 'Axes', attribute: 'Axis minimum/maximum', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Numeric range' },
  { group: 'Axes', attribute: 'Axis interval', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Distance between scale marks' },
  { group: 'Axes', attribute: 'Axis label rotation', line_chart: '✓', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Rotation of category labels' },
  { group: 'Axes', attribute: 'Zero baseline', line_chart: '△', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Whether values begin from zero; especially important for bars' },
  { group: 'Grid', attribute: 'Grid visibility', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '—', meaning: 'Whether chart grid lines appear' },
  { group: 'Grid', attribute: 'Grid colour', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '—', meaning: 'Grid-line colour' },
  { group: 'Grid', attribute: 'Grid style', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '—', meaning: 'Solid, dotted, dashed, etc.' },
  { group: 'Grid', attribute: 'Horizontal grid', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '—', meaning: 'Horizontal reference lines' },
  { group: 'Grid', attribute: 'Vertical grid', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '—', meaning: 'Vertical reference lines' },
  { group: 'Series styling', attribute: 'Series colour', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '△', text: '△', meaning: 'Line colour, bar colour or highlighted text colour' },
  { group: 'Series styling', attribute: 'Multiple-series palette', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '△', meaning: 'Colour set for multiple series or text categories' },
  { group: 'Series styling', attribute: 'Series opacity', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '△', text: '△', meaning: 'Transparency of line, bar or text emphasis' },
  { group: 'Series styling', attribute: 'Series visibility', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Whether a series or text section is shown' },
  { group: 'Line-specific', attribute: 'Line width', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Thickness of the line' },
  { group: 'Line-specific', attribute: 'Line style', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Solid, dashed, dotted, stepped, etc.' },
  { group: 'Line-specific', attribute: 'Curve type', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Straight, smooth, stepped, monotone, etc.' },
  { group: 'Line-specific', attribute: 'Point marker visibility', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Whether points appear on the line' },
  { group: 'Line-specific', attribute: 'Point marker shape', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Circle, square, diamond, etc.' },
  { group: 'Line-specific', attribute: 'Point marker size', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Size of line markers' },
  { group: 'Line-specific', attribute: 'Point marker colour', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Marker fill or border colour' },
  { group: 'Line-specific', attribute: 'Area fill', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Optional shaded area beneath the line' },
  { group: 'Line-specific', attribute: 'Area-fill opacity', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Transparency of the shaded area' },
  { group: 'Line-specific', attribute: 'Connect missing values', line_chart: '✓', bar_chart: '—', table: '—', kpi_card: '—', text: '—', meaning: 'Whether gaps in data are connected' },
  { group: 'Bar-specific', attribute: 'Bar fill colour', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Colour inside each bar' },
  { group: 'Bar-specific', attribute: 'Bar border colour', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Outline colour of bars' },
  { group: 'Bar-specific', attribute: 'Bar border width', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Outline thickness' },
  { group: 'Bar-specific', attribute: 'Bar width', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Thickness of individual bars' },
  { group: 'Bar-specific', attribute: 'Bar gap', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Space between bars' },
  { group: 'Bar-specific', attribute: 'Category gap', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Space between category groups' },
  { group: 'Bar-specific', attribute: 'Bar radius', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Roundness of bar corners' },
  { group: 'Bar-specific', attribute: 'Bar orientation', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Vertical or horizontal' },
  { group: 'Bar-specific', attribute: 'Grouped/stacked mode', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Side-by-side or stacked bars' },
  { group: 'Bar-specific', attribute: 'Stack order', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Ordering of stacked segments' },
  { group: 'Bar-specific', attribute: 'Positive/negative styling', line_chart: '—', bar_chart: '✓', table: '—', kpi_card: '—', text: '—', meaning: 'Different treatment for values above or below zero' },
  { group: 'Text-specific', attribute: 'Text content', line_chart: '—', bar_chart: '—', table: '—', kpi_card: '△', text: '✓', meaning: 'Actual text being displayed' },
  { group: 'Text-specific', attribute: 'Paragraph alignment', line_chart: '—', bar_chart: '—', table: '—', kpi_card: '△', text: '✓', meaning: 'Left, centre, right or justified' },
  { group: 'Text-specific', attribute: 'Paragraph spacing', line_chart: '—', bar_chart: '—', table: '—', kpi_card: '△', text: '✓', meaning: 'Space before or after paragraphs' },
  { group: 'Text-specific', attribute: 'Indentation', line_chart: '—', bar_chart: '—', table: '—', kpi_card: '—', text: '✓', meaning: 'Left, right or first-line indentation' },
  { group: 'Text-specific', attribute: 'Word wrapping', line_chart: '—', bar_chart: '—', table: '△', kpi_card: '△', text: '✓', meaning: 'Whether long text wraps' },
  { group: 'Text-specific', attribute: 'Text overflow', line_chart: '—', bar_chart: '—', table: '△', kpi_card: '△', text: '✓', meaning: 'Clip, ellipsis, scroll, expand, etc.' },
  { group: 'Text-specific', attribute: 'Maximum lines', line_chart: '—', bar_chart: '—', table: '—', kpi_card: '△', text: '✓', meaning: 'Maximum number of displayed lines' },
  { group: 'Text-specific', attribute: 'White-space handling', line_chart: '—', bar_chart: '—', table: '—', kpi_card: '—', text: '✓', meaning: 'Preserve, collapse or wrap spaces' },
  { group: 'Text-specific', attribute: 'List style', line_chart: '—', bar_chart: '—', table: '—', kpi_card: '—', text: '✓', meaning: 'Bullets, numbers, nested lists, etc.' },
  { group: 'Text-specific', attribute: 'Heading level', line_chart: '—', bar_chart: '—', table: '—', kpi_card: '△', text: '✓', meaning: 'Heading 1, Heading 2, paragraph, caption, etc.' },
  { group: 'Text-specific', attribute: 'Emphasis', line_chart: '—', bar_chart: '—', table: '△', kpi_card: '✓', text: '✓', meaning: 'Bold, italic, highlight or callout' },
  { group: 'Text-specific', attribute: 'Hyperlink style', line_chart: '—', bar_chart: '—', table: '△', kpi_card: '—', text: '✓', meaning: 'Link colour, underline and hover behaviour' },
  { group: 'Labels', attribute: 'Data-label visibility', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Whether values are shown directly' },
  { group: 'Labels', attribute: 'Data-label position', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '△', text: '△', meaning: 'Above point, inside bar, end of bar, inline text, etc.' },
  { group: 'Labels', attribute: 'Data-label colour', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Value-label colour' },
  { group: 'Labels', attribute: 'Data-label format', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '△', meaning: 'Currency, percentage, decimal, abbreviated value' },
  { group: 'Labels', attribute: 'Label collision handling', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '△', meaning: 'Hide, rotate, wrap or reposition overlapping labels' },
  { group: 'Legend', attribute: 'Legend visibility', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '△', meaning: 'Whether the category/series key is shown' },
  { group: 'Legend', attribute: 'Legend position', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '△', meaning: 'Top, bottom, left or right' },
  { group: 'Legend', attribute: 'Legend font', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '△', meaning: 'Typography used in legend' },
  { group: 'Legend', attribute: 'Legend marker style', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '—', text: '△', meaning: 'Line, square, circle or text indicator' },
  { group: 'Interaction', attribute: 'Tooltip visibility', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '△', text: '△', meaning: 'Hover information' },
  { group: 'Interaction', attribute: 'Tooltip style', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '△', text: '△', meaning: 'Background, border, font and value format' },
  { group: 'Interaction', attribute: 'Hover effect', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Highlight behaviour on pointer movement' },
  { group: 'Interaction', attribute: 'Click action', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Drill-down, navigation, selection, etc.' },
  { group: 'Interaction', attribute: 'Selection style', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Appearance of a selected point, bar or text section' },
  { group: 'Interaction', attribute: 'Zoom', line_chart: '✓', bar_chart: '△', table: '—', kpi_card: '—', text: '—', meaning: 'Zooming into chart data' },
  { group: 'Interaction', attribute: 'Pan', line_chart: '✓', bar_chart: '△', table: '—', kpi_card: '—', text: '—', meaning: 'Moving across a larger chart' },
  { group: 'Animation', attribute: 'Initial animation', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Appearance when first rendered' },
  { group: 'Animation', attribute: 'Animation duration', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Length of animation' },
  { group: 'Animation', attribute: 'Animation easing', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Motion pattern' },
  { group: 'Animation', attribute: 'Update transition', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Behaviour when data or content changes' },
  { group: 'Responsive behaviour', attribute: 'Desktop layout', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Presentation on large screens' },
  { group: 'Responsive behaviour', attribute: 'Tablet layout', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Presentation on medium screens' },
  { group: 'Responsive behaviour', attribute: 'Mobile layout', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Presentation on small screens' },
  { group: 'Responsive behaviour', attribute: 'Responsive font scaling', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Font-size adjustment by viewport' },
  { group: 'Responsive behaviour', attribute: 'Label reduction', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '△', text: '△', meaning: 'Hide or shorten labels on smaller screens' },
  { group: 'Responsive behaviour', attribute: 'Orientation switch', line_chart: '△', bar_chart: '✓', table: '△', kpi_card: '—', text: '△', meaning: 'Example: vertical bars become horizontal' },
  { group: 'Accessibility', attribute: 'Accessible title', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Descriptive label for assistive technology' },
  { group: 'Accessibility', attribute: 'Alternative description', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Textual explanation of the content' },
  { group: 'Accessibility', attribute: 'Keyboard navigation', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Keyboard-based interaction' },
  { group: 'Accessibility', attribute: 'Focus style', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Visible focus indicator' },
  { group: 'Accessibility', attribute: 'High-contrast mode', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Accessible colour treatment' },
  { group: 'Accessibility', attribute: 'Colour-blind-safe palette', line_chart: '✓', bar_chart: '✓', table: '△', kpi_card: '△', text: '△', meaning: 'Palette that does not rely only on colour' },
  { group: 'Accessibility', attribute: 'Minimum font size', line_chart: '✓', bar_chart: '✓', table: '✓', kpi_card: '✓', text: '✓', meaning: 'Readability constraint' },
];

export const VIEWPORTS = [
  { id: 'desktop', label: 'Desktop', width: '100%' },
  { id: 'tablet', label: 'Tablet', width: '768px' },
  { id: 'mobile', label: 'Mobile', width: '390px' },
  { id: 'print', label: 'Print width', width: '720px' },
];

export const STORAGE_KEY = 'pbmp-form-workbench-v2';
